version: "3"
services:
    app:
        build: ./noiz-front-end
        image: noiz-front-end
        container_name: noiz-front-end
        restart: always
        environment:
            - VUE_APP_API_URL="http://localhost:3000/api/v1/"
        ports:
            - "80:80"
    api:
        build: ./noiz-back-end
        image: noiz-back-end
        container_name: noiz-back-end
        environment:
            - PORT=3000
        ports:
            - 3000:3000
